GO
CREATE PROCEDURE REGISTER_USER 
    @FIRSTNAME NVARCHAR(30), @LASTNAME NVARCHAR(30), @EMAIL NVARCHAR(40),@PASSWORD NVARCHAR(30)
AS
BEGIN
    IF ((SELECT COUNT(*) FROM USERS WHERE EMAIL = @EMAIL) > 0) RETURN 0;
    ELSE 
    BEGIN 
        INSERT INTO USERS VALUES(@FIRSTNAME,@LASTNAME,3,@EMAIL,@PASSWORD,@EMAIL);
        RETURN 1;
        END
END;
GO
ALTER TABLE USERS ALTER COLUMN LOGIN nvarchar(15) NULL;

Go
drop procedure dbo.REGISTER_USER;

Go
CREATE PROCEDURE REGISTER_USER 
    @FIRSTNAME NVARCHAR(30), @LASTNAME NVARCHAR(30), @EMAIL NVARCHAR(40), @PASSWORD NVARCHAR(30)
AS
BEGIN
    IF ((SELECT COUNT(*) FROM USERS WHERE EMAIL = @EMAIL) > 0) RETURN 0;
    ELSE 
    BEGIN 
        INSERT INTO USERS (FIRSTNAME, LASTNAME, IDROLE, PASSWORD, EMAIL) VALUES(@FIRSTNAME,@LASTNAME,3,@PASSWORD,@EMAIL);
        RETURN 1;
    END
END;
