/****** Object:  Table [dbo].[DISEASES]    Script Date: 13.04.2018 12:52:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISEASES](
	[DISEASEID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](3) NOT NULL,
	[DISEASENAME] [nvarchar](255) NOT NULL,
	[SUBCATEGORYID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DISEASEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ICATEGORIES]    Script Date: 13.04.2018 12:52:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ICATEGORIES](
	[CATEGORYCODE] [int] NOT NULL,
	[CATEGORYNAME] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CATEGORYCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBCATEGORIES]    Script Date: 13.04.2018 12:52:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBCATEGORIES](
	[SUBCATEGORIEID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTCODE] [nvarchar](3) NOT NULL,
	[LASTCODE] [nvarchar](3) NOT NULL,
	[CATEGORYID] [int] NULL,
	[SUBCATEGORYNAME] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SUBCATEGORIEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUBDISEASES]    Script Date: 13.04.2018 12:52:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBDISEASES](
	[SUBDISEASEID] [int] IDENTITY(1,1) NOT NULL,
	[SUBDISEASECODE] [nvarchar](5) NOT NULL,
	[SUBDISEASENAME] [nvarchar](255) NOT NULL,
	[DISEASEID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SUBDISEASEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DISEASES]  WITH CHECK ADD FOREIGN KEY([SUBCATEGORYID])
REFERENCES [dbo].[SUBCATEGORIES] ([SUBCATEGORIEID])
GO
ALTER TABLE [dbo].[SUBCATEGORIES]  WITH CHECK ADD FOREIGN KEY([CATEGORYID])
REFERENCES [dbo].[ICATEGORIES] ([CATEGORYCODE])
GO
ALTER TABLE [dbo].[SUBDISEASES]  WITH CHECK ADD FOREIGN KEY([DISEASEID])
REFERENCES [dbo].[DISEASES] ([DISEASEID])
