IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_USER_INFO_START_PAGE')
DROP PROC GET_USER_INFO_START_PAGE

GO
CREATE PROCEDURE GET_USER_INFO_START_PAGE
    @EMAIL NVARCHAR(40)
AS
BEGIN
    IF ((SELECT COUNT(*) FROM USERS WHERE EMAIL = @EMAIL) = 0) RETURN 0;
    ELSE 
    BEGIN 
        SELECT USERS.IDUsers, USERS.FIRSTNAME, USERS.LASTNAME, ROLES.ROLENAME, USERS.PASSWORD, USERS.EMAIL
		FROM USERS INNER JOIN ROLES 
		ON USERS.IDROLE=ROLES.IDRoles
		WHERE EMAIL = @EMAIL
		
		RETURN 1;
    END
END;