IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DOCTORS_RULES_SET')
	BEGIN
		DROP TABLE DOCTORS_RULES_SET;
	END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RULESETS')
	BEGIN
		DROP TABLE RULESETS;
	END
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RULES') 
	BEGIN 
		DROP TABLE RULES
	END

	BEGIN
		CREATE TABLE RULES (
			ID INT IDENTITY(1,1) PRIMARY KEY,
			NAME NVARCHAR(50) UNIQUE NOT NULL,
			HOUR_START TIME NOT NULL,
			HOUR_END TIME NOT NULL,
			PERIOD_START DATE NOT NULL,
			PERIOD_END DATE NOT NULL,
			INCLUSIVE BIT NOT NULL DEFAULT 1,
            SUNDAY BIT NOT NULL DEFAULT 0,
            MONDAY BIT NOT NULL DEFAULT 1,
            TUESDAY BIT NOT NULL DEFAULT 1,
            WEDNESDAY BIT NOT NULL DEFAULT 1,
            THIRSDAY BIT NOT NULL DEFAULT 1,
            FRIDAY BIT NOT NULL DEFAULT 1,
            SATURDAY BIT NOT NULL DEFAULT 0,
            CONSTRAINT PROPER_TIME_FRAME  CHECK (HOUR_END > HOUR_START AND PERIOD_END >= PERIOD_START)
		);
	END;
	
	BEGIN
		CREATE TABLE RULESETS (
			ID INT IDENTITY(1,1) PRIMARY KEY,
			DOCTOR_ID INT FOREIGN KEY REFERENCES DOCTORS(IDDoctors) ON DELETE CASCADE,
			RULE_ID INT FOREIGN KEY REFERENCES RULES(ID) ON DELETE CASCADE
		)
	END;
