IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RULES')
	BEGIN
		ALTER TABLE RULES ALTER COLUMN HOUR_START TIME(0) NOT NULL;
		ALTER TABLE RULES ALTER COLUMN HOUR_END TIME(0) NOT NULL;
	END;