IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_WORKING_HOURS')

DROP PROC GET_WORKING_HOURS;

GO
CREATE PROCEDURE GET_WORKING_HOURS
	@IDDoctors INT
AS  
BEGIN
SELECT HOURSTART, HOURFINISH FROM DOCTORS
WHERE IDDoctors=@IDDoctors;
END;
