IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'VISITS') 
	DROP TABLE VISITS

CREATE TABLE VISITS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	IDDOCTOR INT NOT NULL FOREIGN KEY REFERENCES DOCTORS(IDDOCTORS),
	IDPATIENT INT NOT NULL FOREIGN KEY REFERENCES USERS(IDUSERS),
	DAY DATE NOT NULL, 
	HOUR TIME(0) NOT NULL
);