IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_DOCTORS_WITH_RULE')
DROP PROC GET_DOCTORS_WITH_RULE;
GO
CREATE PROCEDURE GET_DOCTORS_WITH_RULE
@ID int
AS
BEGIN
SELECT * FROM RULESETS WHERE RULE_ID = @ID;
END;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ASSIGN_DOCTOR_TO_RULE')
DROP PROC ASSIGN_DOCTOR_TO_RULE;
GO
CREATE PROCEDURE ASSIGN_DOCTOR_TO_RULE
@DOCTOR_ID int, @RULE_ID int
AS
BEGIN
INSERT INTO RULESETS VALUES (@DOCTOR_ID,@RULE_ID);
END;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'DISMISS_DOCTOR_FROM_RULE')
DROP PROC DISMISS_DOCTOR_FROM_RULE;
GO
CREATE PROCEDURE DISMISS_DOCTOR_FROM_RULE
@ID int
AS
BEGIN
DELETE FROM RULESETS WHERE ID=@ID;
END;