IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RULES')
	BEGIN 
		ALTER TABLE RULES DROP COLUMN HOUR_START;
		ALTER TABLE RULES DROP COLUMN HOER_END;
		ALTER TABLE RULES ADD HOUR_START TIME NOT NULL;
		ALTER TABLE RULES ADD HOUR_END TIME NOT NULL;
	END;