IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DOCTORS_RULES_SET')
	BEGIN
		DROP TABLE DOCTORS_RULES_SET;
	END
ELSE
	BEGIN
		CREATE TABLE DOCTORS_RULES_SET (
			ID INT UNIQUE,
			DOCTOR_ID INT FOREIGN KEY REFERENCES DOCTORS(IDDoctors),
			RULE_ID INT FOREIGN KEY REFERENCES RULES(ID)
		)
	END;
