IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_PROFESSIONS')
DROP PROC GET_PROFESSIONS

GO
CREATE PROCEDURE GET_PROFESSIONS
	@IS_STATIC BIT
AS
BEGIN
SELECT * FROM PROFESSIONS WHERE ISSTATIC = @IS_STATIC;
END;