IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'INSERT_SCHEDULE_RECORD')
	DROP PROC INSERT_SCHEDULE_RECORD

GO
CREATE PROCEDURE INSERT_SCHEDULE_RECORD
    @IDDOCTOR INT, @IDPATIENT INT, @START_DATETIME DATETIME, @END_DATETIME DATETIME
AS
BEGIN
	INSERT INTO SCHEDULE (IDDOCTOR, IDPATIENT, START_DATETIME, END_DATETIME) VALUES(@IDDOCTOR, @IDPATIENT, @START_DATETIME, @END_DATETIME);
END;
