IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RULES') 
	BEGIN 
		DROP TABLE RULES
	END
ELSE
	BEGIN
		CREATE TABLE RULES (
			ID INT PRIMARY KEY,
			NAME NVARCHAR(50) UNIQUE NOT NULL,
			HOUR_START TIME NOT NULL,
			HOER_END TIME NOT NULL,
			IS_ONE_TIME BIT NOT NULL,
			PERIOD_START DATETIME,
			PERIOD_END DATETIME,
			IS_INCLUDE BIT NOT NULL
		);
	END