IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_USER_PASSWORD')
BEGIN
	DROP PROC GET_USER_PASSWORD
END

GO
CREATE PROCEDURE GET_USER_PASSWORD
    @EMAIL NVARCHAR(40)
AS
BEGIN
    IF ((SELECT COUNT(*) FROM USERS WHERE EMAIL = @EMAIL) = 0) RETURN 0;
    ELSE 
    BEGIN 
        SELECT USERS.PASSWORD
		FROM USERS 
		WHERE EMAIL = @EMAIL
		
		RETURN 1;
    END
END;