IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'GET_DOCTORS_BY_PROFESSION_ID')
DROP PROC GET_DOCTORS_BY_PROFESSION_ID;

GO
CREATE PROCEDURE GET_DOCTORS_BY_PROFESSION_ID
	@PROFESSION_ID INT
AS
BEGIN
	SELECT FIRSTNAME, LASTNAME
	FROM USERS
	INNER JOIN DOCTORS ON USERS.IDUSERS = DOCTORS.IDDOCTORS
	WHERE DOCTORS.IDPROFESSION = @PROFESSION_ID;
END;	
